service: slack

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: npm
    packagerOptions:
      lockFile: '../../package-lock.json'
  prune:
    automatic: true
    number: 3

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-create-global-dynamodb-table
  - serverless-prune-plugin
  - serverless-step-functions

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  memorySize: 256

resources:
  Resources:
    SlackSQS:
      Type: AWS::SQS::Queue

stepFunctions:
  stateMachines:
    SlackSF:
      name: SlackMessageStepFunction
      definition:
        StartAt: AddPayloadToSQS
        States:
          AddPayloadToSQS:
            Type: Task
            Resource: arn:aws:states:::sqs:sendMessage.waitForTaskToken
            Parameters:
              QueueUrl:
                Ref: SlackSQS
              MessageBody:
                payload.$: '$'
                taskToken.$: '$$.Task.Token'
            End: true

functions:
  vanity:
    handler: src/handler.main
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - states:SendTaskSuccess
          - states:SendTaskFailure
          - states:StartExecution
        Resource: '*'
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SlackSQS, Arn]
    environment:
      SLACK_TOKEN: ${env:SLACK_TOKEN}
      SLACK_WEBHOOK_PROJ_MEMBER_PORTAL: ${env:SLACK_WEBHOOK_PROJ_MEMBER_PORTAL}
      URL_ROOT: ${env:URL_ROOT}